Add onlyoffice playbook
LibreCodeCoop/ansible-docker pull request #3
Opened 2024-11-18 19:28 UTC by henmohr

@vitormattos, @mateusrovedaa e @nandavereda 

Estou adicionando umas rotinas para facilitar a manutenção. A ideia depois é organizar melhor.

Feedbacks são bem vindos.

2024-12-06 12:33 UTC, vitormattos requested changes

2024-12-06 12:33 UTC, vitormattos commented on onlyoffice-nextcloud-setup.yml
> +        #-
Precisa?
Está comentado, soa que é algo não necessário por ter sido comentado.

2024-12-06 12:33 UTC, vitormattos commented on onlyoffice-setup.yml
> +# Playbook para configurar uma nova instancia do onlyoffice
O outro está em inglês.
Como não é um sistema BR e isto é algo que não está na camada de usuário, acho mais interessante o inglês pois toda a sintaxe é em inglês.

O mesmo comentário vale para os outros valores que estão neste playbook.

2024-12-12 17:22 UTC, henmohr commented on onlyoffice-setup.yml
> +# Playbook para configurar uma nova instancia do onlyoffice
Mudei para PT-BR os outros comentários.

2024-12-12 17:22 UTC, henmohr commented
Precisa ser refinado essa playbook.

2024-12-12 17:22 UTC, closed without merging